# Generated by Django 4.2.5 on 2024-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0003_alter_leavereportstaff_leave_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attendance_date",
            field=models.DateField(),
        ),
    ]
