# Generated by Django 4.2.5 on 2026-10-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_feedback_recipient_staff_mpesapayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('INTERVIEW', 'Interview scheduled'), ('APPROVED', 'Approved'), ('REJECTED', 'Not approved')], default='PENDING', max_length=12)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='index.student')),
            ],
            options={
                'ordering': ['status', '-submitted_at'],
            },
        ),
    ]
