# Generated by Django 5.1.6 on 2025-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_student_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
