# Generated by Django 4.2.5 on 2024-06-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0006_staffs_fcm_token_students_fcm_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_exam_marks", models.FloatField(default=0)),
                ("subject_assignment_marks", models.FloatField(default=0)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.students"
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.subjects"
                    ),
                ),
            ],
        ),
    ]
