# Generated by Django 4.2.5 on 2026-10-07 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_seed_cbc_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectResultSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_result_submissions', to='index.studentclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.subject')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.staff')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Awaiting headteacher review'), ('APPROVED', 'Published to students'), ('REJECTED', 'Returned for correction')], default='SUBMITTED', max_length=12)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publications', to='index.studentclass')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_result_publications', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_result_publications', to='index.staff')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectresultsubmission',
            constraint=models.UniqueConstraint(fields=('class_obj', 'subject', 'academic_year', 'term'), name='unique_class_subject_result_submission'),
        ),
        migrations.AddConstraint(
            model_name='resultpublication',
            constraint=models.UniqueConstraint(fields=('class_obj', 'academic_year', 'term'), name='unique_class_result_publication'),
        ),
    ]
