# Generated by Django 4.2.5 on 2024-06-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0007_studentresult"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotificaionStudent",
            new_name="NotificationStaff",
        ),
        migrations.CreateModel(
            name="NotificationStudent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.students"
                    ),
                ),
            ],
        ),
    ]
